[package]
name = "leven_wasm"
version = "0.1.0"
authors = ["Alex Guerra <alex@heyimalex.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "0.1.2"
wasm-bindgen = "0.2"
